import { NextResponse } from 'next/server';
import { auth } from '@/src/auth/auth';
import { canManageMeetings } from '@/src/auth/roles';
import { pool } from '@/src/db/client';
import { setDbContext } from '@/src/db/context';

const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const bool = (value: unknown) => value === true;
async function getSession(wardId: string) { const session = await auth(); if (!session?.user?.id) return { response: NextResponse.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, { status: 401 }) }; if (!canManageMeetings({ roles: session.user.roles, activeWardId: session.activeWardId }, wardId)) return { response: NextResponse.json({ error: 'Forbidden', code: 'FORBIDDEN' }, { status: 403 }) }; return { session }; }

export async function GET(_: Request, context: { params: Promise<{ wardId: string; meetingId: string }> }) { const { wardId, meetingId } = await context.params; const access = await getSession(wardId); if (access.response) return access.response; const client = await pool.connect(); try { await client.query('BEGIN'); await setDbContext(client, { userId: access.session.user.id, wardId }); const result = await client.query(`SELECT tc.id, tc.meeting_id, tc.owner_name, tc.room_ready, tc.audio_ready, tc.stream_ready, tc.accessibility_checked, tc.authorized_link, tc.start_confirmed_at, tc.stop_confirmed_at, tc.recording_deletion_reminder FROM meeting_technology_checklist tc JOIN meeting m ON m.id = tc.meeting_id AND m.ward_id = tc.ward_id WHERE tc.ward_id = $1::uuid AND tc.meeting_id = $2::uuid`, [wardId, meetingId]); await client.query('COMMIT'); return NextResponse.json({ checklist: result.rows[0] ?? null }); } catch { await client.query('ROLLBACK'); return NextResponse.json({ error: 'Failed to load technology checklist', code: 'INTERNAL_ERROR' }, { status: 500 }); } finally { client.release(); } }

export async function PATCH(request: Request, context: { params: Promise<{ wardId: string; meetingId: string }> }) { const { wardId, meetingId } = await context.params; const access = await getSession(wardId); if (access.response) return access.response; const body = await request.json().catch(() => null) as Record<string, unknown> | null; const link = text(body?.authorizedLink); if (link && !/^https:\/\//i.test(link)) return NextResponse.json({ error: 'Authorized link must use HTTPS', code: 'BAD_REQUEST' }, { status: 400 }); const client = await pool.connect(); try { await client.query('BEGIN'); await setDbContext(client, { userId: access.session.user.id, wardId }); const meeting = await client.query('SELECT id FROM meeting WHERE id = $1::uuid AND ward_id = $2::uuid FOR SHARE', [meetingId, wardId]); if (!meeting.rowCount) { await client.query('ROLLBACK'); return NextResponse.json({ error: 'Meeting not found', code: 'NOT_FOUND' }, { status: 404 }); } const result = await client.query(`INSERT INTO meeting_technology_checklist (ward_id, meeting_id, owner_name, room_ready, audio_ready, stream_ready, accessibility_checked, authorized_link, start_confirmed_at, stop_confirmed_at, recording_deletion_reminder) VALUES ($1::uuid, $2::uuid, NULLIF($3::text, ''), $4::boolean, $5::boolean, $6::boolean, $7::boolean, NULLIF($8::text, ''), CASE WHEN $9::boolean THEN COALESCE((SELECT start_confirmed_at FROM meeting_technology_checklist WHERE ward_id = $1::uuid AND meeting_id = $2::uuid), now()) ELSE NULL END, CASE WHEN $10::boolean THEN COALESCE((SELECT stop_confirmed_at FROM meeting_technology_checklist WHERE ward_id = $1::uuid AND meeting_id = $2::uuid), now()) ELSE NULL END, $11::boolean) ON CONFLICT (ward_id, meeting_id) DO UPDATE SET owner_name = EXCLUDED.owner_name, room_ready = EXCLUDED.room_ready, audio_ready = EXCLUDED.audio_ready, stream_ready = EXCLUDED.stream_ready, accessibility_checked = EXCLUDED.accessibility_checked, authorized_link = EXCLUDED.authorized_link, start_confirmed_at = EXCLUDED.start_confirmed_at, stop_confirmed_at = EXCLUDED.stop_confirmed_at, recording_deletion_reminder = EXCLUDED.recording_deletion_reminder, updated_at = now() RETURNING id, meeting_id, owner_name, room_ready, audio_ready, stream_ready, accessibility_checked, authorized_link, start_confirmed_at, stop_confirmed_at, recording_deletion_reminder`, [wardId, meetingId, text(body?.ownerName), bool(body?.roomReady), bool(body?.audioReady), bool(body?.streamReady), bool(body?.accessibilityChecked), link, bool(body?.startConfirmed), bool(body?.stopConfirmed), bool(body?.recordingDeletionReminder)]); await client.query('COMMIT'); return NextResponse.json({ checklist: result.rows[0] }); } catch { await client.query('ROLLBACK'); return NextResponse.json({ error: 'Failed to save technology checklist', code: 'INTERNAL_ERROR' }, { status: 500 }); } finally { client.release(); } }
