import { NextResponse } from 'next/server';
import { auth } from '@/src/auth/auth';
import { canManageMeetings } from '@/src/auth/roles';
import { pool } from '@/src/db/client';
import { setDbContext } from '@/src/db/context';
import { INTERVIEW_STATUSES } from '@/src/leadership/interviews';

const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
async function access(wardId: string) { const session = await auth(); if (!session?.user?.id) return { response: NextResponse.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, { status: 401 }) }; if (!canManageMeetings({ roles: session.user.roles, activeWardId: session.activeWardId }, wardId)) return { response: NextResponse.json({ error: 'Forbidden', code: 'FORBIDDEN' }, { status: 403 }) }; return { session }; }

export async function GET(_: Request, context: { params: Promise<{ wardId: string }> }) { const { wardId } = await context.params; const allowed = await access(wardId); if (allowed.response) return allowed.response; const client = await pool.connect(); try { await client.query('BEGIN'); await setDbContext(client, { userId: allowed.session.user.id, wardId }); const result = await client.query(`SELECT id, interview_type, member_name, interviewer_name, scheduled_at, status, linked_action_id, linked_calling_id, completed_at FROM scheduled_interview WHERE ward_id = $1::uuid ORDER BY scheduled_at ASC`, [wardId]); await client.query('COMMIT'); return NextResponse.json({ interviews: result.rows }); } catch { await client.query('ROLLBACK'); return NextResponse.json({ error: 'Failed to load interviews', code: 'INTERNAL_ERROR' }, { status: 500 }); } finally { client.release(); } }

export async function POST(request: Request, context: { params: Promise<{ wardId: string }> }) { const { wardId } = await context.params; const allowed = await access(wardId); if (allowed.response) return allowed.response; const body = await request.json().catch(() => null) as { interviewType?: string; memberName?: string; interviewerName?: string; scheduledAt?: string; linkedActionId?: string; linkedCallingId?: string; privateNote?: string } | null; const interviewType = text(body?.interviewType); const memberName = text(body?.memberName); const interviewerName = text(body?.interviewerName); const scheduledAt = text(body?.scheduledAt); if (!interviewType || !memberName || !interviewerName || !scheduledAt || Number.isNaN(Date.parse(scheduledAt))) return NextResponse.json({ error: 'Invalid interview payload', code: 'BAD_REQUEST' }, { status: 400 }); const client = await pool.connect(); try { await client.query('BEGIN'); await setDbContext(client, { userId: allowed.session.user.id, wardId }); const result = await client.query(`INSERT INTO scheduled_interview (ward_id, interview_type, member_name, interviewer_name, scheduled_at, linked_action_id, linked_calling_id, private_note, created_by_user_id) VALUES ($1::uuid, $2::text, $3::text, $4::text, $5::timestamptz, NULLIF($6::text, '')::uuid, NULLIF($7::text, '')::uuid, NULLIF($8::text, ''), $9::uuid) RETURNING id, interview_type, member_name, interviewer_name, scheduled_at, status, linked_action_id, linked_calling_id, completed_at`, [wardId, interviewType, memberName, interviewerName, scheduledAt, text(body?.linkedActionId), text(body?.linkedCallingId), text(body?.privateNote), allowed.session.user.id]); await client.query('COMMIT'); return NextResponse.json({ interview: result.rows[0] }, { status: 201 }); } catch { await client.query('ROLLBACK'); return NextResponse.json({ error: 'Failed to create interview', code: 'INTERNAL_ERROR' }, { status: 500 }); } finally { client.release(); } }

export { INTERVIEW_STATUSES };
