export const DOCUMENT_TYPES = ['SACRAMENT_PROGRAM'] as const;
export const PAPER_SIZES = ['LETTER', 'A4'] as const;
export const ORIENTATIONS = ['PORTRAIT', 'LANDSCAPE'] as const;
export const FOLD_TYPES = ['NONE', 'BIFOLD', 'TRIFOLD', 'HALF_SHEET'] as const;
export const BLOCK_WIDTHS = ['FULL', 'TWO_THIRDS', 'HALF', 'ONE_THIRD'] as const;
export const DATA_MODES = ['AUTO', 'AUTO_OVERRIDE', 'MANUAL'] as const;
export const TEMPLATE_SCOPES = ['SYSTEM', 'STAKE', 'WARD', 'PERSONAL_DRAFT'] as const;
export const TEMPLATE_STATUSES = ['DRAFT', 'PUBLISHED', 'ARCHIVED'] as const;
export const LOCK_LEVELS = ['NONE', 'REGION', 'BLOCK', 'CONFIGURATION'] as const;
export const LOCK_PROPERTIES = ['POSITION', 'SIZE', 'CONTENT', 'STYLE', 'VISIBILITY'] as const;
export const VISIBILITY_MODES = ['VISIBLE', 'HIDDEN', 'HIDE_WHEN_EMPTY'] as const;
export const PRINT_BEHAVIORS = ['PRINT_AND_DIGITAL', 'PRINT_ONLY', 'DIGITAL_ONLY'] as const;
export const DIGITAL_BEHAVIORS = ['NORMAL', 'LINK'] as const;
export const THEME_FONT_FAMILIES = ['SYSTEM_SANS', 'SERIF', 'MONOSPACE'] as const;
export const SCHEMA_VERSIONS = [1] as const;

export const BLOCK_TYPES = [
  'DOCUMENT_TITLE',
  'WARD_NAME',
  'MEETING_INFO',
  'MEETING_PROGRAM',
  'PRESIDING_CONDUCTING',
  'MUSIC_LEADERS',
  'SPEAKERS',
  'WARD_STAKE_BUSINESS',
  'WARD_LEADERSHIP',
  'MISSIONARIES_SERVING',
  'MISSIONARIES_ASSIGNED',
  'WARD_CONTACT',
  'BUILDING_INFO',
  'SERVICE_TIMES',
  'ANNOUNCEMENTS',
  'UPCOMING_EVENTS',
  'CALENDAR',
  'THIS_WEEK',
  'SUNDAY_LESSONS',
  'YOUTH_ACTIVITIES',
  'PRIMARY_ACTIVITIES',
  'TEMPLE_INFO',
  'SCRIPTURE',
  'QUOTE',
  'CUSTOM_TEXT',
  'IMAGE',
  'DIVIDER',
  'SPACER',
  'QR_CODE',
  'CUSTOM_LINK'
] as const;

export const DEFAULT_DOCUMENT_ID = '00000000-0000-4000-8000-000000000001';
export const DEFAULT_PAGE_ID = '00000000-0000-4000-8000-000000000002';
export const DEFAULT_REGION_ID = '00000000-0000-4000-8000-000000000003';
export const DEFAULT_BLOCK_ID = '00000000-0000-4000-8000-000000000004';
