-- Create standard_calling reference table
CREATE TABLE IF NOT EXISTS standard_calling (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  organization TEXT,
  unit_type TEXT NOT NULL DEFAULT 'ward',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed ward callings
INSERT INTO standard_calling (name, organization, unit_type, sort_order) VALUES
  ('Bishop', 'Bishopric', 'ward', 1),
  ('First Counselor in the Bishopric', 'Bishopric', 'ward', 2),
  ('Second Counselor in the Bishopric', 'Bishopric', 'ward', 3),
  ('Executive Secretary', 'Bishopric', 'ward', 4),
  ('Ward Clerk', 'Bishopric', 'ward', 5),
  ('Assistant Ward Clerk', 'Bishopric', 'ward', 6),
  ('Assistant Ward Clerk (Finance)', 'Bishopric', 'ward', 7),
  ('Assistant Ward Clerk (Membership)', 'Bishopric', 'ward', 8),
  ('Elders Quorum President', 'Elders Quorum', 'ward', 10),
  ('First Counselor in the Elders Quorum Presidency', 'Elders Quorum', 'ward', 11),
  ('Second Counselor in the Elders Quorum Presidency', 'Elders Quorum', 'ward', 12),
  ('Elders Quorum Secretary', 'Elders Quorum', 'ward', 13),
  ('Elders Quorum Instructor', 'Elders Quorum', 'ward', 14),
  ('Relief Society President', 'Relief Society', 'ward', 20),
  ('First Counselor in the Relief Society Presidency', 'Relief Society', 'ward', 21),
  ('Second Counselor in the Relief Society Presidency', 'Relief Society', 'ward', 22),
  ('Relief Society Secretary', 'Relief Society', 'ward', 23),
  ('Relief Society Teacher', 'Relief Society', 'ward', 24),
  ('Relief Society Ministering Secretary', 'Relief Society', 'ward', 25),
  ('Young Men President', 'Young Men', 'ward', 30),
  ('First Counselor in the Young Men Presidency', 'Young Men', 'ward', 31),
  ('Second Counselor in the Young Men Presidency', 'Young Men', 'ward', 32),
  ('Young Men Secretary', 'Young Men', 'ward', 33),
  ('Priests Quorum Adviser', 'Young Men', 'ward', 34),
  ('Teachers Quorum Adviser', 'Young Men', 'ward', 35),
  ('Deacons Quorum Adviser', 'Young Men', 'ward', 36),
  ('Young Women President', 'Young Women', 'ward', 40),
  ('First Counselor in the Young Women Presidency', 'Young Women', 'ward', 41),
  ('Second Counselor in the Young Women Presidency', 'Young Women', 'ward', 42),
  ('Young Women Secretary', 'Young Women', 'ward', 43),
  ('Young Women Adviser', 'Young Women', 'ward', 44),
  ('Young Women Camp Director', 'Young Women', 'ward', 45),
  ('Primary President', 'Primary', 'ward', 50),
  ('First Counselor in the Primary Presidency', 'Primary', 'ward', 51),
  ('Second Counselor in the Primary Presidency', 'Primary', 'ward', 52),
  ('Primary Secretary', 'Primary', 'ward', 53),
  ('Primary Music Leader', 'Primary', 'ward', 54),
  ('Primary Pianist', 'Primary', 'ward', 55),
  ('Activity Days Leader', 'Primary', 'ward', 56),
  ('Nursery Leader', 'Primary', 'ward', 57),
  ('Sunday School President', 'Sunday School', 'ward', 60),
  ('First Counselor in the Sunday School Presidency', 'Sunday School', 'ward', 61),
  ('Second Counselor in the Sunday School Presidency', 'Sunday School', 'ward', 62),
  ('Sunday School Secretary', 'Sunday School', 'ward', 63),
  ('Sunday School Teacher', 'Sunday School', 'ward', 64),
  ('Ward Mission Leader', 'Ward Mission', 'ward', 70),
  ('Ward Missionary', 'Ward Mission', 'ward', 71),
  ('Ward Temple and Family History Consultant', 'Temple and Family History', 'ward', 80),
  ('Ward Temple and Family History Leader', 'Temple and Family History', 'ward', 81),
  ('Ward Music Coordinator', 'Music', 'ward', 90),
  ('Ward Choir Director', 'Music', 'ward', 91),
  ('Ward Organist', 'Music', 'ward', 92),
  ('Sacrament Meeting Chorister', 'Music', 'ward', 93),
  ('Ward Accompanist', 'Music', 'ward', 94),
  ('Self-Reliance Specialist', 'Self-Reliance and Welfare', 'ward', 100),
  ('Welfare Specialist', 'Self-Reliance and Welfare', 'ward', 101),
  ('Employment Specialist', 'Self-Reliance and Welfare', 'ward', 102),
  ('Ward Communications Director', 'Other Ward Callings', 'ward', 110),
  ('Ward Newsletter Editor', 'Other Ward Callings', 'ward', 111),
  ('Ward Historian', 'Other Ward Callings', 'ward', 112),
  ('Ward Emergency Preparedness Specialist', 'Other Ward Callings', 'ward', 113),
  ('Ward Librarian', 'Other Ward Callings', 'ward', 114),
  ('Assistant Ward Librarian', 'Other Ward Callings', 'ward', 115),
  ('Sunday Meeting Schedule Coordinator', 'Other Ward Callings', 'ward', 116)
ON CONFLICT (name) DO NOTHING;

-- Seed stake callings
INSERT INTO standard_calling (name, organization, unit_type, sort_order) VALUES
  ('Stake President', 'Stake Presidency', 'stake', 1),
  ('First Counselor in the Stake Presidency', 'Stake Presidency', 'stake', 2),
  ('Second Counselor in the Stake Presidency', 'Stake Presidency', 'stake', 3),
  ('Stake Executive Secretary', 'Stake Presidency', 'stake', 4),
  ('Stake Clerk', 'Stake Presidency', 'stake', 5),
  ('Assistant Stake Clerk', 'Stake Presidency', 'stake', 6),
  ('Assistant Stake Clerk (Finance)', 'Stake Presidency', 'stake', 7),
  ('Assistant Stake Clerk (Membership)', 'Stake Presidency', 'stake', 8),
  ('Patriarch', 'Stake Presidency', 'stake', 9),
  ('High Councilor', 'High Council', 'stake', 10),
  ('Stake Relief Society President', 'Stake Relief Society', 'stake', 20),
  ('First Counselor in the Stake Relief Society Presidency', 'Stake Relief Society', 'stake', 21),
  ('Second Counselor in the Stake Relief Society Presidency', 'Stake Relief Society', 'stake', 22),
  ('Stake Relief Society Secretary', 'Stake Relief Society', 'stake', 23),
  ('Stake Young Men President', 'Stake Young Men', 'stake', 30),
  ('First Counselor in the Stake Young Men Presidency', 'Stake Young Men', 'stake', 31),
  ('Second Counselor in the Stake Young Men Presidency', 'Stake Young Men', 'stake', 32),
  ('Stake Young Men Secretary', 'Stake Young Men', 'stake', 33),
  ('Stake Young Women President', 'Stake Young Women', 'stake', 40),
  ('First Counselor in the Stake Young Women Presidency', 'Stake Young Women', 'stake', 41),
  ('Second Counselor in the Stake Young Women Presidency', 'Stake Young Women', 'stake', 42),
  ('Stake Young Women Secretary', 'Stake Young Women', 'stake', 43),
  ('Stake Primary President', 'Stake Primary', 'stake', 50),
  ('First Counselor in the Stake Primary Presidency', 'Stake Primary', 'stake', 51),
  ('Second Counselor in the Stake Primary Presidency', 'Stake Primary', 'stake', 52),
  ('Stake Primary Secretary', 'Stake Primary', 'stake', 53),
  ('Stake Sunday School President', 'Stake Sunday School', 'stake', 60),
  ('First Counselor in the Stake Sunday School Presidency', 'Stake Sunday School', 'stake', 61),
  ('Second Counselor in the Stake Sunday School Presidency', 'Stake Sunday School', 'stake', 62),
  ('Stake Sunday School Secretary', 'Stake Sunday School', 'stake', 63),
  ('Stake Music Coordinator', 'Stake Music', 'stake', 70),
  ('Stake Choir Director', 'Stake Music', 'stake', 71),
  ('Stake Organist', 'Stake Music', 'stake', 72),
  ('Stake Historian', 'Other Stake Callings', 'stake', 80),
  ('Stake Communications Director', 'Other Stake Callings', 'stake', 81),
  ('Stake Temple and Family History Consultant', 'Other Stake Callings', 'stake', 82)
ON CONFLICT (name) DO NOTHING;

-- Seed branch callings
INSERT INTO standard_calling (name, organization, unit_type, sort_order) VALUES
  ('Branch President', 'Branch Presidency', 'branch', 1),
  ('First Counselor in the Branch Presidency', 'Branch Presidency', 'branch', 2),
  ('Second Counselor in the Branch Presidency', 'Branch Presidency', 'branch', 3),
  ('Branch Executive Secretary', 'Branch Presidency', 'branch', 4),
  ('Branch Clerk', 'Branch Presidency', 'branch', 5),
  ('Assistant Branch Clerk', 'Branch Presidency', 'branch', 6),
  ('Branch Elders Quorum President', 'Elders Quorum', 'branch', 10),
  ('First Counselor in the Branch Elders Quorum Presidency', 'Elders Quorum', 'branch', 11),
  ('Second Counselor in the Branch Elders Quorum Presidency', 'Elders Quorum', 'branch', 12),
  ('Branch Elders Quorum Secretary', 'Elders Quorum', 'branch', 13),
  ('Branch Relief Society President', 'Relief Society', 'branch', 20),
  ('First Counselor in the Branch Relief Society Presidency', 'Relief Society', 'branch', 21),
  ('Second Counselor in the Branch Relief Society Presidency', 'Relief Society', 'branch', 22),
  ('Branch Relief Society Secretary', 'Relief Society', 'branch', 23),
  ('Branch Young Men President', 'Young Men', 'branch', 30),
  ('Branch Young Women President', 'Young Women', 'branch', 40),
  ('Branch Primary President', 'Primary', 'branch', 50),
  ('First Counselor in the Branch Primary Presidency', 'Primary', 'branch', 51),
  ('Second Counselor in the Branch Primary Presidency', 'Primary', 'branch', 52),
  ('Branch Sunday School President', 'Sunday School', 'branch', 60),
  ('Branch Mission Leader', 'Branch Mission', 'branch', 70),
  ('Branch Music Coordinator', 'Music', 'branch', 80)
ON CONFLICT (name) DO NOTHING;

-- Seed district callings
INSERT INTO standard_calling (name, organization, unit_type, sort_order) VALUES
  ('District President', 'District Presidency', 'district', 1),
  ('First Counselor in the District Presidency', 'District Presidency', 'district', 2),
  ('Second Counselor in the District Presidency', 'District Presidency', 'district', 3),
  ('District Executive Secretary', 'District Presidency', 'district', 4),
  ('District Clerk', 'District Presidency', 'district', 5),
  ('Assistant District Clerk', 'District Presidency', 'district', 6),
  ('District Relief Society President', 'District Relief Society', 'district', 20),
  ('First Counselor in the District Relief Society Presidency', 'District Relief Society', 'district', 21),
  ('Second Counselor in the District Relief Society Presidency', 'District Relief Society', 'district', 22),
  ('District Relief Society Secretary', 'District Relief Society', 'district', 23),
  ('District Young Men President', 'District Young Men', 'district', 30),
  ('District Young Women President', 'District Young Women', 'district', 40),
  ('District Primary President', 'District Primary', 'district', 50),
  ('First Counselor in the District Primary Presidency', 'District Primary', 'district', 51),
  ('Second Counselor in the District Primary Presidency', 'District Primary', 'district', 52),
  ('District Sunday School President', 'District Sunday School', 'district', 60),
  ('District Historian', 'Other District Callings', 'district', 70),
  ('District Mission Leader', 'District Mission', 'district', 80)
ON CONFLICT (name) DO NOTHING;
