'use client';
import { useState } from 'react';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { INTERVIEW_STATUSES } from '@/src/leadership/interviews';

type Interview = { id: string; interview_type: string; member_name: string; interviewer_name: string; scheduled_at: string; status: string };
export function InterviewsClient({ wardId, initial }: { wardId: string; initial: Interview[] }) { const [items, setItems] = useState(initial); const [type, setType] = useState('Membership or ordinance'); const [member, setMember] = useState(''); const [interviewer, setInterviewer] = useState(''); const [when, setWhen] = useState(''); const [error, setError] = useState('');
 async function create(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch(`/api/w/${wardId}/interviews`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ interviewType: type, memberName: member, interviewerName: interviewer, scheduledAt: new Date(when).toISOString() }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? 'Could not schedule interview'); return; } setItems((current) => [...current, body.interview].sort((a, b) => a.scheduled_at.localeCompare(b.scheduled_at))); setMember(''); setInterviewer(''); setWhen(''); }
 async function update(item: Interview, status: string) { const response = await fetch(`/api/w/${wardId}/interviews/${item.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? 'Could not update interview'); return; } setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, status } : entry)); }
 return <div className="space-y-6"><section className="rounded-lg border bg-card p-5 shadow-sm"><h2 className="text-lg font-semibold">Schedule interview</h2><form onSubmit={create} className="mt-3 grid gap-2 sm:grid-cols-2"><input required value={type} onChange={(e) => setType(e.target.value)} placeholder="Interview type" className="rounded-md border bg-background px-3 py-2 text-sm"/><input required value={member} onChange={(e) => setMember(e.target.value)} placeholder="Member" className="rounded-md border bg-background px-3 py-2 text-sm"/><input required value={interviewer} onChange={(e) => setInterviewer(e.target.value)} placeholder="Interviewer" className="rounded-md border bg-background px-3 py-2 text-sm"/><input required type="datetime-local" value={when} onChange={(e) => setWhen(e.target.value)} className="rounded-md border bg-background px-3 py-2 text-sm" aria-label="Interview date and time"/><button className={cn(buttonVariants({ size: 'sm' }))}>Schedule</button></form>{error ? <p className="mt-2 text-sm text-destructive">{error}</p> : null}</section><section className="space-y-3"><h2 className="text-lg font-semibold">Interview schedule</h2>{items.length ? items.map((item) => <article key={item.id} className="rounded-lg border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{item.member_name}</h3><p className="text-sm text-muted-foreground">{item.interview_type} · {item.interviewer_name} · {new Date(item.scheduled_at).toLocaleString()}</p></div><select value={item.status} onChange={(e) => update(item, e.target.value)} className="rounded-md border bg-background px-2 py-1 text-sm" aria-label={`Status for ${item.member_name}`}>{INTERVIEW_STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}</select></div></article>) : <p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No interviews scheduled.</p>}</section></div>; }
