import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(import.meta.dirname, '..');
const outputPath = path.join(root, 'docs', 'DEPENDENCY_GRAPH.md');
const sourceExtensions = new Set(['.js', '.mjs', '.ts', '.tsx']);
const ignoredDirectories = new Set(['.git', '.next', 'coverage', 'node_modules', 'playwright-report', 'test-results']);

async function walk(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.isDirectory() && ignoredDirectories.has(entry.name)) continue;
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(absolute)));
    else if (sourceExtensions.has(path.extname(entry.name))) files.push(absolute);
  }
  return files;
}

function importsFrom(source) {
  const imports = [];
  const patterns = [
    /(?:import|export)\s+(?:[\s\S]*?\s+from\s+)?['"]([^'"]+)['"]/g,
    /\bimport\(\s*['"]([^'"]+)['"]\s*\)/g,
    /\brequire\(\s*['"]([^'"]+)['"]\s*\)/g
  ];
  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) imports.push(match[1]);
  }
  return imports;
}

function area(relativePath) {
  const parts = relativePath.split('/');
  if (parts[0] === 'apps' && parts[1] === 'web') {
    if (parts[2] === 'app') return parts[3] === 'api' ? 'web:api' : 'web:app';
    if (parts[2] === 'components' || parts[2] === 'lib') return 'web:ui';
    if (parts[2] === 'src') return `web:${parts[3] ?? 'core'}`;
    if (parts[2] === 'scripts') return 'web:tooling';
    return 'web:config';
  }
  if (parts[0] === 'packages') return `package:${parts[1]}`;
  if (parts[0] === 'scripts') return 'root:tooling';
  return 'root:other';
}

function externalPackage(specifier) {
  if (specifier.startsWith('node:')) return 'Node.js';
  if (specifier.startsWith('@')) return specifier.split('/').slice(0, 2).join('/');
  return specifier.split('/')[0];
}

function resolveInternal(importer, specifier, files) {
  let candidate;
  if (specifier.startsWith('@/')) candidate = path.join(root, 'apps/web', specifier.slice(2));
  else if (specifier.startsWith('.')) candidate = path.resolve(path.dirname(importer), specifier);
  else return null;
  const attempts = [
    candidate,
    ...[...sourceExtensions].map((ext) => candidate + ext),
    ...[...sourceExtensions].map((ext) => path.join(candidate, `index${ext}`))
  ];
  return attempts.find((attempt) => files.has(attempt)) ?? null;
}

function markdownEscape(value) {
  return value.replaceAll('|', '\\|');
}

async function generate() {
  const absoluteFiles = (await walk(root)).sort();
  const fileSet = new Set(absoluteFiles);
  const fileData = [];
  const areaFiles = new Map();
  const internalEdges = new Map();
  const externalEdges = new Map();

  for (const file of absoluteFiles) {
    const relative = path.relative(root, file).replaceAll(path.sep, '/');
    const sourceArea = area(relative);
    areaFiles.set(sourceArea, (areaFiles.get(sourceArea) ?? 0) + 1);
    const specifiers = importsFrom(await fs.readFile(file, 'utf8'));
    let internalCount = 0;
    let externalCount = 0;
    for (const specifier of specifiers) {
      const target = resolveInternal(file, specifier, fileSet);
      if (target) {
        internalCount++;
        const key = `${sourceArea}\0${area(path.relative(root, target).replaceAll(path.sep, '/'))}`;
        internalEdges.set(key, (internalEdges.get(key) ?? 0) + 1);
      } else if (!specifier.startsWith('.') && !specifier.startsWith('@/')) {
        externalCount++;
        const key = `${sourceArea}\0${externalPackage(specifier)}`;
        externalEdges.set(key, (externalEdges.get(key) ?? 0) + 1);
      }
    }
    fileData.push({ relative, sourceArea, internalCount, externalCount });
  }

  const areas = [...areaFiles].sort(([a], [b]) => a.localeCompare(b));
  const ids = new Map(areas.map(([name], index) => [name, `A${index + 1}`]));
  const internalRows = [...internalEdges]
    .map(([key, count]) => [...key.split('\0'), count])
    .sort((a, b) => b[2] - a[2] || a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));
  const externalRows = [...externalEdges]
    .map(([key, count]) => [...key.split('\0'), count])
    .sort((a, b) => b[2] - a[2] || a[0].localeCompare(b[0]));
  const lines = [
    '# Code Dependency Graph',
    '',
    '> Generated by `npm run docs:dependencies`. Do not edit generated tables or diagrams by hand.',
    '',
    'This index statically scans JavaScript and TypeScript imports. It groups files into architectural areas so the graph remains readable, while the file index preserves per-file dependency counts. Dynamic imports with non-literal paths, runtime database relationships, SQL dependencies, framework routing, and infrastructure configuration are outside its scope.',
    '',
    '## Architectural graph',
    '',
    'An arrow means that the source area imports the target area. Labels are the number of import statements (not necessarily unique files). Self-references are omitted from the diagram and retained in the table below.',
    '',
    '```mermaid',
    'flowchart LR',
    ...areas.map(([name, count]) => `  ${ids.get(name)}["${name}<br/>${count} files"]`),
    ...internalRows.filter(([from, to]) => from !== to).map(([from, to, count]) => `  ${ids.get(from)} -->|${count}| ${ids.get(to)}`),
    '```',
    '',
    '## Area inventory',
    '',
    '| Area | Source files |',
    '| --- | ---: |',
    ...areas.map(([name, count]) => `| \`${name}\` | ${count} |`),
    '',
    '## Internal dependencies',
    '',
    '| Importing area | Imported area | Imports |',
    '| --- | --- | ---: |',
    ...internalRows.map(([from, to, count]) => `| \`${from}\` | \`${to}\` | ${count} |`),
    '',
    '## External dependencies',
    '',
    '| Importing area | Package/runtime | Imports |',
    '| --- | --- | ---: |',
    ...externalRows.map(([from, dependency, count]) => `| \`${from}\` | \`${dependency}\` | ${count} |`),
    '',
    '## File index',
    '',
    '| File | Area | Internal imports | External imports |',
    '| --- | --- | ---: | ---: |',
    ...fileData.map(
      ({ relative, sourceArea, internalCount, externalCount }) =>
        `| \`${markdownEscape(relative)}\` | \`${sourceArea}\` | ${internalCount} | ${externalCount} |`
    ),
    '',
    '## Regenerating and validating',
    '',
    '- Run `npm run docs:dependencies` after changing module imports or adding source files.',
    '- Run `npm run docs:dependencies:check` in CI or locally to fail when this document is stale.',
    '- Review new cross-area edges carefully, especially dependencies that bypass the authentication, ward-context, or database layers.',
    ''
  ].join('\n');
  return lines;
}

const generated = await generate();
if (process.argv.includes('--check')) {
  const current = await fs.readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    console.error('docs/DEPENDENCY_GRAPH.md is stale; run npm run docs:dependencies');
    process.exitCode = 1;
  }
} else {
  await fs.writeFile(outputPath, generated);
  console.log('Wrote docs/DEPENDENCY_GRAPH.md');
}
