'use client';
import { useState } from 'react';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';

type Meeting = { id: string; meeting_date: string; meeting_type: string };
type Checklist = { owner_name: string | null; room_ready: boolean; audio_ready: boolean; stream_ready: boolean; accessibility_checked: boolean; authorized_link: string | null; recording_deletion_reminder: boolean; start_confirmed_at: string | null; stop_confirmed_at: string | null };
export function TechnologyClient({ wardId, meetings }: { wardId: string; meetings: Meeting[] }) { const [meetingId, setMeetingId] = useState(meetings[0]?.id ?? ''); const [checklist, setChecklist] = useState<Checklist | null>(null); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false); const selected = meetings.find((meeting) => meeting.id === meetingId);
 async function load(id: string) { setMeetingId(id); setLoaded(false); const response = await fetch(`/api/w/${wardId}/meetings/${id}/technology`); const body = await response.json(); if (!response.ok) { setError(body.error ?? 'Could not load checklist'); return; } setChecklist(body.checklist ?? { owner_name: '', room_ready: false, audio_ready: false, stream_ready: false, accessibility_checked: false, authorized_link: '', recording_deletion_reminder: false, start_confirmed_at: null, stop_confirmed_at: null }); setLoaded(true); }
 async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { ownerName: form.get('ownerName'), authorizedLink: form.get('authorizedLink'), roomReady: form.get('roomReady') === 'on', audioReady: form.get('audioReady') === 'on', streamReady: form.get('streamReady') === 'on', accessibilityChecked: form.get('accessibilityChecked') === 'on', recordingDeletionReminder: form.get('recordingDeletionReminder') === 'on', startConfirmed: form.get('startConfirmed') === 'on', stopConfirmed: form.get('stopConfirmed') === 'on' }; const response = await fetch(`/api/w/${wardId}/meetings/${meetingId}/technology`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? 'Could not save checklist'); return; } setChecklist(body.checklist); }
 return <div className="space-y-4"><select value={meetingId} onChange={(e) => load(e.target.value)} className="rounded-md border bg-background px-3 py-2 text-sm" aria-label="Meeting">{meetings.map((meeting) => <option key={meeting.id} value={meeting.id}>{meeting.meeting_date} · {meeting.meeting_type}</option>)}</select>{meetingId && !loaded ? <button type="button" onClick={() => load(meetingId)} className={cn(buttonVariants({ variant: 'outline' }))}>Load checklist</button> : null}{checklist && selected ? <form onSubmit={save} className="grid gap-3 rounded-lg border bg-card p-5 sm:grid-cols-2"><p className="sm:col-span-2 text-sm text-muted-foreground">{selected.meeting_date} · {selected.meeting_type}. Never store streaming credentials here.</p><input name="ownerName" defaultValue={checklist.owner_name ?? ''} placeholder="Checklist owner" className="rounded-md border bg-background px-3 py-2 text-sm"/><input name="authorizedLink" defaultValue={checklist.authorized_link ?? ''} placeholder="Authorized stream link (HTTPS)" className="rounded-md border bg-background px-3 py-2 text-sm"/>{[['roomReady','Room ready',checklist.room_ready],['audioReady','Audio ready',checklist.audio_ready],['streamReady','Stream ready',checklist.stream_ready],['accessibilityChecked','Accessibility checked',checklist.accessibility_checked],['recordingDeletionReminder','Recording deletion reminder',checklist.recording_deletion_reminder],['startConfirmed','Start confirmed',Boolean(checklist.start_confirmed_at)],['stopConfirmed','Stop confirmed',Boolean(checklist.stop_confirmed_at)]].map(([name,label,checked]) => <label key={String(name)} className="flex items-center gap-2 text-sm"><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)}/>{String(label)}</label>)}<button className={cn(buttonVariants({ size: 'sm' }))}>Save checklist</button></form> : null}{error ? <p className="text-sm text-destructive">{error}</p> : null}</div>; }
